#!/usr/bin/env python3
"""Remove every file generated by build_kernel.py."""

from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
KERNEL = ROOT / "bin" / "KERNEL.SYS"


def main():
    removed = []
    if BUILD.is_dir():
        shutil.rmtree(BUILD)
        removed.append(BUILD)
    elif BUILD.exists():
        BUILD.unlink()
        removed.append(BUILD)

    if KERNEL.is_file() or KERNEL.is_symlink():
        KERNEL.unlink()
        removed.append(KERNEL)

    for cache in ROOT.rglob("__pycache__"):
        if cache.is_dir():
            shutil.rmtree(cache)
            removed.append(cache)
    for bytecode in ROOT.rglob("*.py[co]"):
        bytecode.unlink()
        removed.append(bytecode)

    if removed:
        for path in removed:
            print(f"removed: {path.relative_to(ROOT)}")
    else:
        print("already clean")


if __name__ == "__main__":
    main()
